# Generated by Django 5.0.7 on 2024-07-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_date_creates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='date_creates',
            new_name='date_created',
        ),
    ]
